### ISSUE TITLE
Update to support rocket =0.5.0-rc.4

### ISSUE THREAD

**Issue by kije** [kolbma/rocket-governor#10]
First off, thanks for this great crate! :)

Rocket `0.5.0-rc.4` was just released with several [breaking changes](https://github.com/SergioBenitez/Rocket/blob/v0.5.0-rc.4/CHANGELOG.md#breaking-changes).

Relevant for rocket-governor seems to be:

- `Outcome::Failure` was renamed to [Outcome::Error](https://api.rocket.rs/v0.5-rc/rocket/outcome/enum.Outcome.html#variant.Error).

```console

error[E0599]: no variant or associated item named `Failure` found for enum `Outcome` in the current scope
   --> /.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-governor-0.1.0-rc.4/src/lib.rs:234:34
    |
234 |                         Outcome::Failure((Status::TooManyRequests, e))
    |                                  ^^^^^^^ variant or associated item not found in `Outcome<_, (Status, _), Status>`

error[E0599]: no variant or associated item named `Failure` found for enum `Outcome` in the current scope
   --> /.cargo/registry/src/index.crates.io-6f17d22bba15001f/rocket-governor-0.1.0-rc.4/src/lib.rs:236:35
    |
236 |                     _ => Outcome::Failure((Status::BadRequest, e)),
    |                                   ^^^^^^^ variant or associated item not found in `Outcome<_, (Status, _), Status>`


```

**Comment by LCrossman** [comment]
Hi, this is a great crate! I agree that the change is Outcome::Failure to Outcome::Error and this also works on Mac OSX

**Comment by kolbma** [comment]
Thank you guys.  
At the moment I'm not so engaged with rocket.  
But there will be shortly a new release v0.2.0-rc.1 supporting rocket v0.5 release.

Please report if it works for you (or close the issue afterwards)!

**Comment by kolbma** [comment]
It's available https://crates.io/crates/rocket-governor/0.2.0-rc.1
