### ISSUE TITLE
Use RateLimitingMiddleware when released

### ISSUE THREAD

**Issue by kolbma** [kolbma/rocket-governor#2]
In master branch of governor there is a `RateLimitingMiddleware` feature which can be used to get information about current rate limiting state and quota.

This might be the possibility to set the HTTP headers on limits correctly. And circumvent the need to capsule governor `Quota` in the inner of another struct to collect settings.

https://github.com/antifuchs/governor/pull/67

**Comment by kolbma** [comment]
There is also this [governor/issues/66](https://github.com/antifuchs/governor/issues/66) with some information.

**Comment by antifuchs** [comment]
It took a while, but now 0.4.0 is out, with the middleware change: https://crates.io/crates/governor/0.4.0

**Comment by kolbma** [comment]
@antifuchs Thanks for info. Need to finish some other stuff before I can continue with this.

**Comment by kolbma** [comment]
Releasing https://github.com/kolbma/rocket-governor/releases/tag/v0.1.0-rc.1 with using governor middleware.
